# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=150),
        ),
    ]
